language: java
jdk:
  - oraclejdk8

dist: trusty
sudo: required

env:
  global:
    - VERSION_BASE='1.0'

services:
  - docker

cache:
  directories:
    - $HOME/.m2

before_install:
  - export CI_WORK_DIRECTORY="${TRAVIS_BUILD_DIR}/.ci" && mkdir -p $CI_WORK_DIRECTORY
  - git clone -b travis https://github.com/mkorman9/jenkins_scripts $CI_WORK_DIRECTORY/
  - chmod +x $CI_WORK_DIRECTORY/*.sh $CI_WORK_DIRECTORY/common_dependencies/*.sh

install:
  - . $CI_WORK_DIRECTORY/common_dependencies/redis.sh
  - . $CI_WORK_DIRECTORY/common_dependencies/mariadb.sh --dbname test --username test --password test
  - . $CI_WORK_DIRECTORY/common_dependencies/activemq.sh --username test --password test
  - . $CI_WORK_DIRECTORY/common_dependencies/config_server.sh --port 18080

script:
  - $CI_WORK_DIRECTORY/invoke.sh || exit 1

notifications:
  email: false
